---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/pushingsk8/public_html/wp-content/themes/blankslate-child
    - /bin/rsync -av --exclude='.git' --exclude='.cpanel.yml' --exclude='node_modules' . $DEPLOYPATH/
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
